# Generated by Django 3.0.5 on 2020-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="event", options={"ordering": ("-date",)},),
        migrations.AddField(
            model_name="event",
            name="num_participants",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
