swagger: '2.0'
info:
  title: events API
  description: events API
  termsOfService: https://en.wikipedia.org/wiki/MIT_License#License_terms
  contact:
    email: alexan.nader@gmail.com
  license:
    name: MIT License
  version: v1
host: localhost
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths: {}
definitions: {}
